"""create initial tables

Revision ID: 170b2516ef3c
Revises: 
Create Date: 2026-08-03 17:05:57.233535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '170b2516ef3c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('profile_summary', sa.String(), nullable=True),
    sa.Column('channels_used', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_profiles_phone_number'), 'client_profiles', ['phone_number'], unique=True)
    op.create_table('unanswered_queries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('user_query', sa.Text(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('channel', sa.Enum('WHATSAPP', 'WEBSITE', name='query_channel_enum'), nullable=False),
    sa.Column('team_notified', sa.Boolean(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unanswered_queries_phone_number'), 'unanswered_queries', ['phone_number'], unique=False)
    op.create_table('call_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_profile_id', sa.UUID(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('added_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_profile_id'], ['client_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_logs_client_profile_id'), 'call_logs', ['client_profile_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_profile_id', sa.UUID(), nullable=False),
    sa.Column('service_category', sa.Enum('WEB_DEVELOPMENT', 'WEB_DESIGN', 'GRAPHIC_DESIGN', 'AI_AUTOMATION', 'CUSTOM_SOFTWARE', 'OTHER', name='service_category_enum'), nullable=False),
    sa.Column('requirement_description', sa.Text(), nullable=True),
    sa.Column('source_channel', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'CONTACTED', 'IN_PROGRESS', 'CLOSED_WON', 'CLOSED_LOST', name='order_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_profile_id'], ['client_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_client_profile_id'), 'orders', ['client_profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_client_profile_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_call_logs_client_profile_id'), table_name='call_logs')
    op.drop_table('call_logs')
    op.drop_index(op.f('ix_unanswered_queries_phone_number'), table_name='unanswered_queries')
    op.drop_table('unanswered_queries')
    op.drop_index(op.f('ix_client_profiles_phone_number'), table_name='client_profiles')
    op.drop_table('client_profiles')
    # ### end Alembic commands ###
