"""add topic to meetings

Revision ID: 1fb28a6bab1c
Revises: 8c9fd38371c8
Create Date: 2026-08-05 13:26:01.001006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fb28a6bab1c'
down_revision: Union[str, Sequence[str], None] = '8c9fd38371c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('topic', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetings', 'topic')
    # ### end Alembic commands ###
