"""add event_link to meetings

Revision ID: 33023414baa4
Revises: ecc75d35eecc
Create Date: 2026-08-05 13:14:19.500805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33023414baa4'
down_revision: Union[str, Sequence[str], None] = 'ecc75d35eecc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('event_link', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetings', 'event_link')
    # ### end Alembic commands ###
