"""add topic and client_name to meetings

Revision ID: 513fd2b009cb
Revises: 1fb28a6bab1c
Create Date: 2026-08-05 13:28:40.373095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '513fd2b009cb'
down_revision: Union[str, Sequence[str], None] = '1fb28a6bab1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('client_name', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetings', 'client_name')
    # ### end Alembic commands ###
