"""add meetings table

Revision ID: ecc75d35eecc
Revises: 170b2516ef3c
Create Date: 2026-08-05 12:50:16.705843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecc75d35eecc'
down_revision: Union[str, Sequence[str], None] = '170b2516ef3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meetings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_profile_id', sa.UUID(), nullable=False),
    sa.Column('google_event_id', sa.String(length=255), nullable=False),
    sa.Column('scheduled_date', sa.String(length=10), nullable=False),
    sa.Column('scheduled_time', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_profile_id'], ['client_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meetings_client_profile_id'), 'meetings', ['client_profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meetings_client_profile_id'), table_name='meetings')
    op.drop_table('meetings')
    # ### end Alembic commands ###
